#!/usr/bin/env sh
set -e
. "$(dirname -- "$0")/_/husky.sh"

number_of_uncommitted_files=$(git status -u --porcelain | wc -l)

npm run format
npm run lint
if [ $number_of_uncommitted_files -ne 0 ]; then
  echo ""
  echo "Error! Detected uncommitted changes..."
  echo "Please commit your changes and try again."
  echo ""
  exit -1
fi
npm run build
npm test
